
spring:
  datasource:
    url: "jdbc:h2:file:./database"
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    initialize: false

  h2:
    console:
      enabled: true
      path: "/h2-console"

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

logging:
  level.root: WARN
  org.springframework: INFO
  org.hibernate: INFO
  kr.co.kware: DEBUG

  path: "./logs/"
